# Generated by Django 5.1.2 on 2024-11-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_price',
            new_name='price',
        ),
    ]
