# Generated by Django 5.1.2 on 2024-11-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_orderavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(),
        ),
    ]
